const tags = ["Music",
    "Game",
    "Nature",
    "Calm",
    "Funny",
    "Startup",
    "Life",
    "Travel",
    "Food",
    "Entrepreneurship",
    "Education",
    "Health",
    "Love",
    "Design",
    "Writing",
    "Technology",
    "Self-Improvement",
    "Business",
    "Sports",
    "Art",
    "Open-Source",
    "Programming"]

module.exports = tags;